### ISSUE TITLE
apatch next10021遇到以下情况该怎么解决呢

### ISSUE THREAD

**Issue by BaiLai7513** [Aurora-Nasa-1/ARMIAS#10]
@
![Screenshot_2024-12-16-16-44-21-551_me garfieldhan apatch next](https://github.com/user-attachments/assets/67a06680-4a5e-412f-9ecd-be596106fa38)
![Screenshot_2024-12-16-16-48-40-941_bin mt plus canary](https://github.com/user-attachments/assets/6bca9c4d-c07e-459d-942d-8ee0e1b75cb5)
![Screenshot_2024-12-16-16-48-47-805_bin mt plus canary](https://github.com/user-attachments/assets/12be8fcb-f163-4b57-9f60-a50ff278ea2b)

**Comment by Aurora-Nasa-1** [comment]
这周末修复

**Comment by Aurora-Nasa-1** [comment]
已于1.0.5修复
