### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by BaiLai7513** [Aurora-Nasa-1/ARMIAS#3]
这个该怎么调整呢
![Screenshot_2024-11-04-00-09-43-948_me garfieldhan apatch next](https://github.com/user-attachments/assets/9d7107b9-8479-4782-9d42-df93de069849)

**Comment by Aurora-Nasa-1** [comment]
你好！关于此问题，请您检查settings.sh中的CustomScript="true"或"false"

**Comment by BaiLai7513** [comment]
反馈，改了兼容模式，改了那个false和true都无法刷入替换/data/adb/tricky_store/目录内容

**Comment by Aurora-Nasa-1** [comment]
对于APatch，似乎有些问题，准备下周兼容

**Comment by BaiLai7513** [comment]
OK

**Comment by Aurora-Nasa-1** [comment]
在自定义脚本中，你或许可以尝试su -c cp -r $MODDIR/patches/data/* /data/

**Comment by Aurora-Nasa-1** [comment]
在自定义脚本中，你或许可以尝试su -c cp -r $MODPATH/patches/data/* /data/
